services:
  web:
    build: .        # <--- usa el Dockerfile
    ports:
    - "8080:80"
    depends_on:
    - db
    volumes:
    - ./html:/var/www/html
    restart: always

  db:
    image: mysql:8.1.0    #check the mysql version you need for your project
    environment:
      MYSQL_ROOT_PASSWORD: root_password    #you can change the mysql root password here
      MYSQL_DATABASE: p10
    ports:
      - "3306:3306"     #you can change the database name here
    volumes:
      - ./mysql_data:/var/lib/mysql 
    restart: always     #this line maps the content of ./mysql_data in your pc to the /var/lib/mysql of the container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"    #this line maps your pc port to the container port
    depends_on:
      - db    #this line links this container to the db container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306   # Puerto donde MySQL estÃ¡ escuchando en el contenedor db
    restart: always
